#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -g -m64 -DL_ENDIAN -DTERMIO -O3 -Wall"
  #define PLATFORM "linux-x86_64"
  #define DATE "Fri Jan 30 12:30:29 CST 2026"
#endif
